#!/bin/sh
echo "🚀 Running pre-commit checks..."

pnpm lint
if [ $? -ne 0 ]; then
  echo "❌ Lint failed."
  exit 1
fi

pnpm typecheck
if [ $? -ne 0 ]; then
  echo "❌ Typecheck failed."
  exit 1
fi

pnpm test
if [ $? -ne 0 ]; then
  echo "❌ Tests failed."
  exit 1
fi

echo "✅ All checks passed. Proceeding with commit..."
exit 0